Fixing infrastructure

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -15,6 +15,48 @@ jobs:
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
     steps:
+      - name: Check for secret RANDOM_SEED
+        run: |
+          if [[ -z "${{ secrets.RANDOM_SEED }}" ]]; then
+            echo "Required secret RANDOM_SEED is missing"
+            exit 1
+          fi
+      - name: Check for secret ACM_CERTIFICATE_ARN
+        run: |
+        if [[ -z "${{ secrets.ACM_CERTIFICATE_ARN }}" ]]; then
+          echo "Required secret ACM_CERTIFICATE_ARN is missing"
+          exit 1
+        fi
+      - name: Check for secret LAMBDA_ROLE_ARN
+        run: |
+          if [[ -z "${{ secrets.LAMBDA_ROLE_ARN }}" ]]; then
+            echo "Required secret LAMBDA_ROLE_ARN is missing"
+            exit 1
+          fi
+      - name: Check for secret AWS_ACCESS_KEY_ID
+        run: |
+          if [[ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]]; then
+            echo "Required secret AWS_ACCESS_KEY_ID is missing"
+            exit 1
+          fi
+      - name: Check for secret AWS_SECRET_ACCESS_KEY
+        run: |
+          if [[ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]]; then
+            echo "Required secret AWS_SECRET_ACCESS_KEY is missing"
+            exit 1
+          fi
+      - name: Check for secret AWS_REGION
+        run: |
+          if [[ -z "${{ secrets.AWS_REGION }}" ]]; then
+            echo "Required secret AWS_REGION is missing"
+            exit 1
+          fi
+      - name: Check for secret SNS_ARN
+        run: |
+          if [[ -z "${{ secrets.SNS_ARN }}" ]]; then
+            echo "Required secret SNS_ARN is missing"
+            exit 1
+          fi
       - name: Get current time
         uses: srfrnk/current-time@master
         id: time
@@ -49,7 +91,7 @@ jobs:
       - name: Upload lambda package to S3
         run: aws s3 cp ${{ github.sha }}.zip s3://code-and-coffee-service-deploy-${{ secrets.RANDOM_SEED }}/${{ github.sha }}.zip
       - name: Execute CloudFormation runtime infrastructure template
-        run: aws cloudformation deploy --template-file runtime.template.yaml --stack-name code-and-coffee-service --parameter-overrides DeployBucketName=${{ secrets.S3_DEPLOY_BUCKET_NAME }} LambdaKey=${{ github.sha }}.zip AcmCertificateArn=${{ secrets.ACM_CERTIFICATE_ARN }} RandomSeed=${{ secrets.RANDOM_SEED }} LambdaRoleArn=${{ secrets.LAMBDA_ROLE_ARN }}
+        run: aws cloudformation deploy --template-file runtime.template.yaml --stack-name code-and-coffee-service --parameter-overrides LambdaKey=${{ github.sha }}.zip AcmCertificateArn=${{ secrets.ACM_CERTIFICATE_ARN }} RandomSeed=${{ secrets.RANDOM_SEED }} LambdaRoleArn=${{ secrets.LAMBDA_ROLE_ARN }}
       - name: Upload dist to web resources bucket
         run: aws s3 sync dist s3://code-and-coffee-service-web-resources
       - name: Publish SNS topic success
